#cloud-config
package_update: true
package_upgrade: all

packages:
  # base utils
  - sudo
  - bash-completion
  - less
  - jq
  - curl
  - wget
  - gnupg2
  # system utils
  - tmux
  - vim
  - mc
  - ca-certificates
  - logrotate
  - git
  - chrony
  - apt-transport-https
  - unattended-upgrades
  # netwok utils
  - iproute2
  - tcpdump
  - nmap
  - traceroute
  - dnsutils
  # disk utils
  - tree
  - unzip
  - rsync
  - parted
  - lvm2
  - xfsprogs
  # monitroing utils
  - sysstat
  - strace
  - lsof
  - htop
  - iotop
  - iftop
  - smem
  # cloud utils
  - qemu-guest-agent


ansible:
  package_name: ansible-core
  install_method: distro
  pull:
    - url: https://github.com/metrika-online/linux-common.git
      playbook_names: local.yaml

#runcmd:
#  - |
#    ansible-pull -U https://github.com/metrika-online/linux-common.git local.yaml
#    echo '*/30 * * * * root ansible-pull -U https://github.com/metrika-online/linux-common.git local.yaml | sudo tee /etc/cron.d/ansible-pull-updates

final_message: "Linux common configuration completed successfully"
