#cloud-config
package_update: true
package_upgrade: all

packages:
  # base utils
  - sudo
  - bash-completion
  - less
  - jq
  - curl
  - wget
  - gnupg2
  # system utils
  - tmux
  - vim
  - mc
  - ca-certificates
  - logrotate
  - git
  - chrony
  - apt-transport-https
  - unattended-upgrades
  # netwok utils
  - iproute2
  - tcpdump
  - nmap
  - traceroute
  # disk utils
  - tree
  - unzip
  - rsync
  - parted
  - lvm2
  - xfsprogs
  # monitroing utils
  - sysstat
  - strace
  - lsof
  - htop
  - iotop
  - iftop
  - smem
  # cloud utils
  - qemu-guest-agent
  - ansible
  - cloud-guest-utils

bootcmd:
  - |
    DISK_ID="scsi-0QEMU_QEMU_HARDDISK_drive-scsi1"
    DISK_DEV="/dev/disk/by-id/${DISK_ID}"
    PARTITION_DEV="${DISK_DEV}-part1"
    
    if [ -b "${DISK_DEV}" ] && ! lsblk "${DISK_DEV}" | grep -q "part" 2>/dev/null; then
      # Создаем раздел с помощью fdisk через перенаправление ввода
      echo -e "g\nn\n1\n\n\nw" | fdisk "${DISK_DEV}"
      pvcreate "${PARTITION_DEV}"
      vgcreate vg_data "${PARTITION_DEV}"
      lvcreate -n lv_data -l 100%FREE vg_data
      mkfs.xfs /dev/vg_data/lv_data
    fi

runcmd:
  - ansible-pull -U https://github.com/metrika-online/linux-common.git local.yaml
  - echo '*/30 * * * * root ansible-pull -U https://github.com/metrika-online/linux-common.git local.yaml' > /etc/cron.d/ansible-pull-updates

final_message: "Linux common configuration completed successfully"
