#cloud-config
package_update: true
package_upgrade: all

packages:
  # base utils
  - sudo
  - bash-completion
  - less
  - jq
  - curl
  - wget
  - gnupg2
  # system utils
  - tmux
  - vim
  - mc
  - ca-certificates
  - logrotate
  - git
  - chrony
  - apt-transport-https
  - unattended-upgrades
  # netwok utils
  - iproute2
  - tcpdump
  - nmap
  - traceroute
  # disk utils
  - tree
  - unzip
  - rsync
  - parted
  - lvm2
  - xfsprogs
  # monitroing utils
  - sysstat
  - strace
  - lsof
  - htop
  - iotop
  - iftop
  - smem
  # cloud utils
  - qemu-guest-agent
  - ansible
  - cloud-guest-utils

bootcmd:
  - |
    if [ -b /dev/sdb ] && ! parted /dev/sdb print >/dev/null 2>&1; then
      parted /dev/sdb mklabel gpt --script
      parted /dev/sdb mkpart primary 0% 100% --script
      pvcreate /dev/sdb1
      vgcreate vg_data /dev/sdb1
      lvcreate -n lv_data -l 100%FREE vg_data
      mkfs.xfs /dev/vg_data/lv_data
    fi

runcmd:
  - ansible-pull -U https://github.com/metrika-online/linux-common.git local.yaml
  - echo '*/30 * * * * root ansible-pull -U https://github.com/metrika-online/linux-common.git local.yaml' > /etc/cron.d/ansible-pull-updates

final_message: "Linux common configuration completed successfully"
