#cloud-config
include:
  - https://raw.githubusercontent.com/metrika-online/linux-ci-snippets/refs/heads/main/linux-common.yaml
packages:
  - curl
  - tzdata
  - postfix

runcmd:
  - |
    curl -sS https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | sudo bash
    
final_message: "GitLab configuration completed successfully"
