#cloud-config
package_update: true
package_upgrade: all

packages:
  - git
  - ansible

runcmd:
  - |
    ansible-pull -U https://github.com/metrika-online/linux-common.git local.yaml
    echo '*/30 * * * * root ansible-pull -U https://github.com/metrika-online/linux-common.git local.yaml | sudo tee /etc/cron.d/ansible-pull-updates

final_message: "Linux common configuration completed successfully"
