#cloud-config
merge_how:
 - name: list
   settings: [append]
 - name: dict
   settings: [no_replace, recurse_list]
  
package_update: true
package_upgrade: all

packages:
  - git
  - ansible

bootcmd:
  - |
    DISK_ID="scsi-0QEMU_QEMU_HARDDISK_drive-scsi1"
    DISK_DEV="/dev/disk/by-id/${DISK_ID}"
    PARTITION_DEV="${DISK_DEV}-part1"
    
    if [ -b "${DISK_DEV}" ] && ! [ -b "${PARTITION_DEV}" ]; then
      # Создаем GPT таблицу и раздел на всем диске
      echo 'label: gpt
      ,,' | sfdisk "${DISK_DEV}"
      sleep 5
      # Проверяем, что раздел создался
      if [ -b "${PARTITION_DEV}" ]; then
        # Создаем LVM на созданном разделе
        pvcreate "${PARTITION_DEV}"
        vgcreate vg_data "${PARTITION_DEV}"
        lvcreate -n lv_data -l 100%FREE vg_data
        mkfs.xfs /dev/vg_data/lv_data -f
      fi
    fi

runcmd:
  - ansible-pull -U https://github.com/metrika-online/linux-common.git local.yaml -v
  - echo '*/30 * * * * root ansible-pull -U https://github.com/metrika-online/linux-common.git local.yaml' > /etc/cron.d/ansible-pull-updates

final_message: "Linux common configuration completed successfully"
