#cloud-config
merge_how:
 - name: list
   settings: [append]
 - name: dict
   settings: [no_replace, recurse_list]

packages:
  - tzdata
  - ca-certificates
  - apt-transport-https
  - gnupg
  - curl

runcmd:
  - curl -fsSL "https://packages.gitlab.com/gitlab/gitlab-ce/gpgkey" | sudo gpg --dearmor -o /usr/share/keyrings/gitlab-archive-keyring.gpg
  - echo "deb [signed-by=/usr/share/keyrings/gitlab-archive-keyring.gpg] https://packages.gitlab.com/gitlab/gitlab-ce/debian bookworm main" | sudo tee /etc/apt/sources.list.d/gitlab_gitlab-ce.list
  - sudo EXTERNAL_URL="https://gitlab.example.com" apt install gitlab-ce -y

final_message: "GitLab configuration completed successfully"
